// Mocks generated by Mockito 5.4.5 from annotations
// in ardennes/test/features/recent_drawing/recent_drawing_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ardennes/libraries/drawing/recent_drawing_service.dart' as _i3;
import 'package:ardennes/models/drawings/drawing_sheet_view_log.dart' as _i5;
import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecentDrawingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecentDrawingService extends _i1.Mock
    implements _i3.RecentDrawingService {
  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  _i4.Stream<List<_i5.DrawingSheetViewLog>> getRecentDrawings({
    required String? projectId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentDrawings,
          [],
          {
            #projectId: projectId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Stream<List<_i5.DrawingSheetViewLog>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<_i5.DrawingSheetViewLog>>.empty(),
      ) as _i4.Stream<List<_i5.DrawingSheetViewLog>>);

  @override
  _i4.Future<void> logDrawingView({
    required String? projectId,
    required String? userId,
    required _i5.DrawingViewLogItem? newItem,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDrawingView,
          [],
          {
            #projectId: projectId,
            #userId: userId,
            #newItem: newItem,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
